import type { GradientState, ColorStop } from '../state/GradientState';

// ── Shared helpers ────────────────────────────────────────────────────────────

function alphaHex(a: number): string {
  return a >= 1 ? '' : Math.round(a * 255).toString(16).padStart(2, '0');
}

function stateToConfig(s: GradientState): string {
  return JSON.stringify({
    colors:           s.colors,
    bgColor:          s.bgColor,
    renderMode:       s.renderMode,
    material:         s.material,
    motionMode:       s.motionMode,
    speed:            s.speed,
    seed:             s.seed,
    grain:            s.grain,
    glowAmount:       s.glowAmount,
    motionIntensity:  s.motionIntensity,
    iridescence:      s.iridescence,
    chromaticAberration: s.chromaticAberration,
    displaceFreqX:    s.displaceFreqX,
    displaceFreqZ:    s.displaceFreqZ,
    displaceAmount:   s.displaceAmount,
    twistFreqX: s.twistFreqX, twistFreqY: s.twistFreqY, twistFreqZ: s.twistFreqZ,
    twistPowX:  s.twistPowX,  twistPowY:  s.twistPowY,  twistPowZ:  s.twistPowZ,
    rotationX:  s.rotationX,  rotationY:  s.rotationY,  rotationZ:  s.rotationZ,
    scaleX:     s.scaleX,     scaleY:     s.scaleY,      scaleZ:     s.scaleZ,
  }, null, 2);
}

function cssMeshLayers(colors: ColorStop[]): string {
  return colors.map((c, i) => {
    const angle = (i / colors.length) * 360;
    const x = Math.round(50 + 38 * Math.cos(angle * Math.PI / 180));
    const y = Math.round(50 + 38 * Math.sin(angle * Math.PI / 180));
    return `  radial-gradient(circle at ${x}% ${y}%, ${c.hex}${alphaHex(c.alpha)}, transparent 65%)`;
  }).join(',\n');
}

// ── CSS (no-JS fallback) ──────────────────────────────────────────────────────

export function genCSS(s: GradientState): string {
  return `/* Mesh Gradient — MeshStudio
   No-JS CSS approximation (static snapshot of the animated gradient).
   For the animated WebGL version, use the Next.js or Vanilla HTML export. */

.mesh-gradient {
  background: ${s.bgColor};
  background-image:
${cssMeshLayers(s.colors)};
}`;
}

// ── Next.js component ─────────────────────────────────────────────────────────

export function genNextJs(s: GradientState): { component: string; loader: string; readme: string } {
  const config = stateToConfig(s);

  const component = `'use client';
/**
 * MeshGradient.tsx — generated by MeshStudio
 * Drop this + mesh-gradient-runtime.js into your Next.js project.
 * See README-nextjs.md for setup instructions.
 */
import { useEffect, useRef } from 'react';
import type { MeshGradientConfig } from './mesh-gradient-runtime';

export const MESH_CONFIG: MeshGradientConfig = ${config};

interface Props {
  className?: string;
  config?: Partial<MeshGradientConfig>;
  speed?: number;
}

export default function MeshGradient({ className = '', config, speed }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const rtRef = useRef<import('./mesh-gradient-runtime').MeshGradientRuntime | null>(null);

  useEffect(() => {
    let mounted = true;
    import('./mesh-gradient-runtime').then(({ MeshGradientRuntime }) => {
      if (!mounted || !canvasRef.current) return;
      const rt = new MeshGradientRuntime();
      rtRef.current = rt;
      rt.mount(canvasRef.current, {
        ...MESH_CONFIG,
        ...config,
        ...(speed !== undefined ? { speed } : {}),
      });
    });
    return () => {
      mounted = false;
      rtRef.current?.dispose();
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <canvas
      ref={canvasRef}
      aria-hidden="true"
      style={{ display: 'block', width: '100%', height: '100%' }}
      className={className}
    />
  );
}`;

  const loader = `// MeshGradientLoader.tsx — SSR-safe dynamic import wrapper
import dynamic from 'next/dynamic';
export const MeshGradient = dynamic(() => import('./MeshGradient'), { ssr: false });`;

  const readme = `# MeshGradient — Next.js Setup

## Files to copy into your project
1. MeshGradient.tsx
2. MeshGradientLoader.tsx
3. mesh-gradient-runtime.js  (from MeshStudio releases)

## Usage
\`\`\`tsx
// app/page.tsx
import { MeshGradient } from '@/components/MeshGradientLoader';

export default function Page() {
  return (
    <div className="relative min-h-screen">
      <MeshGradient className="absolute inset-0 -z-10" />
      <main>Your content here</main>
    </div>
  );
}
\`\`\`

## Runtime props
| Prop       | Type    | Description                     |
|------------|---------|---------------------------------|
| className  | string  | Tailwind / CSS classes          |
| config     | object  | Override any gradient config    |
| speed      | number  | Override animation speed (0-4)  |

## Features built-in
- Pauses automatically when scrolled off-screen (IntersectionObserver)
- Respects prefers-reduced-motion for accessibility
- Responsive resize with ResizeObserver
- DPR capped at 1.5x by default (set config.dprCap to change)
`;

  return { component, loader, readme };
}

// ── React (generic) ───────────────────────────────────────────────────────────

export function genReact(s: GradientState): { component: string; readme: string } {
  const config = stateToConfig(s);

  const component = `/**
 * MeshGradient.tsx — generated by MeshStudio
 * Works with any React 18+ / Vite / CRA project.
 */
import { useEffect, useRef } from 'react';
import type { MeshGradientConfig } from './mesh-gradient-runtime';
import { MeshGradientRuntime } from './mesh-gradient-runtime';

export const MESH_CONFIG: MeshGradientConfig = ${config};

interface Props extends React.HTMLAttributes<HTMLCanvasElement> {
  config?: Partial<MeshGradientConfig>;
}

export function MeshGradient({ config, style, ...rest }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const rtRef = useRef<MeshGradientRuntime | null>(null);

  useEffect(() => {
    if (!canvasRef.current) return;
    const rt = new MeshGradientRuntime();
    rtRef.current = rt;
    rt.mount(canvasRef.current, { ...MESH_CONFIG, ...config });
    return () => rt.dispose();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <canvas
      ref={canvasRef}
      aria-hidden="true"
      style={{ display: 'block', width: '100%', height: '100%', ...style }}
      {...rest}
    />
  );
}`;

  const readme = `# MeshGradient — React Setup

\`\`\`bash
# Copy into src/components/: MeshGradient.tsx, mesh-gradient-runtime.js
\`\`\`

\`\`\`tsx
import { MeshGradient } from './components/MeshGradient';

export function Hero() {
  return (
    <section style={{ position: 'relative', height: '100vh' }}>
      <div style={{ position: 'absolute', inset: 0, zIndex: -1 }}>
        <MeshGradient />
      </div>
      <h1>Your hero content</h1>
    </section>
  );
}
\`\`\`
`;

  return { component, readme };
}

// ── Vanilla HTML ──────────────────────────────────────────────────────────────

export function genVanilla(s: GradientState): string {
  const config = stateToConfig(s);
  const layers = cssMeshLayers(s.colors);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>Mesh Gradient</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { width: 100vw; height: 100vh; overflow: hidden; }
    #mesh-canvas { display: block; width: 100%; height: 100%; }
    .mesh-fallback {
      display: none; width: 100%; height: 100%;
      background: ${s.bgColor};
      background-image:
${layers};
    }
    @media (prefers-reduced-motion: reduce) {
      #mesh-canvas { display: none; }
      .mesh-fallback { display: block; }
    }
  </style>
</head>
<body>
  <canvas id="mesh-canvas" aria-hidden="true"></canvas>
  <div class="mesh-fallback" id="mesh-fallback" aria-hidden="true"></div>

  <script type="module">
    import { MeshGradientRuntime } from './mesh-gradient-runtime.js';

    const config = ${config};
    const canvas = document.getElementById('mesh-canvas');

    try {
      const rt = new MeshGradientRuntime();
      rt.mount(canvas, config);
    } catch (err) {
      console.warn('MeshGradient: WebGL2 unavailable, showing CSS fallback.', err);
      canvas.style.display = 'none';
      document.getElementById('mesh-fallback').style.display = 'block';
    }
  </script>
</body>
</html>`;
}

// ── Web Component ─────────────────────────────────────────────────────────────

export function genWebComponent(s: GradientState): string {
  const config = stateToConfig(s);

  return `/**
 * mesh-gradient.js — Web Component generated by MeshStudio
 *
 * Usage (any HTML/framework):
 *   <script type="module" src="mesh-gradient.js"></script>
 *   <mesh-gradient speed="1" render-mode="blobs"></mesh-gradient>
 *
 * Requires mesh-gradient-runtime.js in the same directory.
 */
import { MeshGradientRuntime } from './mesh-gradient-runtime.js';

const DEFAULT_CONFIG = ${config};

class MeshGradientElement extends HTMLElement {
  static get observedAttributes() {
    return ['colors', 'speed', 'seed', 'render-mode', 'material', 'motion-mode'];
  }

  constructor() {
    super();
    this._rt = null;
    this._canvas = null;
    const shadow = this.attachShadow({ mode: 'open' });
    // Build shadow DOM without innerHTML
    const canvas = document.createElement('canvas');
    canvas.setAttribute('aria-hidden', 'true');
    canvas.style.cssText = 'display:block;width:100%;height:100%';
    shadow.appendChild(canvas);
    this._canvas = canvas;
  }

  connectedCallback() {
    this._rt = new MeshGradientRuntime();
    this._rt.mount(this._canvas, this._buildConfig());
  }

  disconnectedCallback() {
    this._rt?.dispose();
    this._rt = null;
  }

  attributeChangedCallback() {
    this._rt?.update(this._buildConfig());
  }

  _buildConfig() {
    const cfg = { ...DEFAULT_CONFIG };
    const colors = this.getAttribute('colors');
    if (colors) { try { cfg.colors = JSON.parse(colors); } catch {} }
    const speed = this.getAttribute('speed');
    if (speed !== null) cfg.speed = parseFloat(speed);
    const seed  = this.getAttribute('seed');
    if (seed !== null) cfg.seed = parseFloat(seed);
    const rm  = this.getAttribute('render-mode');
    if (rm) cfg.renderMode = rm;
    const mat = this.getAttribute('material');
    if (mat) cfg.material = mat;
    const mm  = this.getAttribute('motion-mode');
    if (mm) cfg.motionMode = mm;
    return cfg;
  }
}

customElements.define('mesh-gradient', MeshGradientElement);`;
}

// ── Media instructions ─────────────────────────────────────────────────────────

export function genMediaInstructions(): string {
  return `## Exporting media from MeshStudio

### PNG (static frame)
Click the "↓ Export PNG" toolbar button, or press P.

### WebM video (animated)
Click "⏺ Record" to start recording, "⏹ Stop" to end.
The video is saved as mesh-gradient-{timestamp}.webm.

### Converting to MP4 (ffmpeg)
  ffmpeg -i mesh-gradient.webm -c:v libx264 -crf 23 -pix_fmt yuv420p output.mp4

### Embedding as CSS background video
  <video autoplay muted loop playsinline
         style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover;z-index:-1">
    <source src="mesh-gradient.mp4" type="video/mp4">
  </video>

### Animated GIF (reduced quality, for social/docs)
  ffmpeg -i mesh-gradient.webm -vf "fps=15,scale=960:-1:flags=lanczos" output.gif`;
}
